[package]
name = "rustun"
version = "0.1.0"
authors = ["scriptjunkie", "skess42"]
edition = "2018"

[dependencies]
libc = "0"
aes-gcm = "0.9"
rand = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
bincode = "1"
reqwest = {version="0.11", features = ["blocking"]}
